import { Box } from "@chakra-ui/react";

const Home = () => {
  return (
    <Box pt={95} h={2000} textAlign="center">
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin convallis sit amet justo quis cursus. Etiam a sagittis risus, non ullamcorper ante. In ullamcorper aliquet tellus, quis porta ante iaculis a. Fusce ultrices erat ut nunc tristique efficitur. Aliquam ac vehicula libero. Sed sed vulputate erat. Nunc pulvinar, arcu a auctor sagittis, tellus purus cursus dolor, a vestibulum ante est sit amet elit. Sed porttitor euismod blandit. Proin tempor dolor at sollicitudin mollis. Pellentesque convallis non libero in pulvinar. Nulla convallis purus sit amet quam sagittis, sit amet feugiat turpis tincidunt. Mauris lorem tortor, molestie vel dictum et, condimentum eget ante. Vivamus iaculis lacus nulla, vehicula porttitor sapien varius at. Fusce luctus ipsum sit amet urna euismod fringilla.

      Duis nisi tortor, commodo non tellus id, faucibus fringilla tortor. Nunc varius et mauris a ultricies. Proin mi enim, feugiat in fermentum et, porta at orci. Curabitur sem ligula, lacinia ut elementum ac, blandit id nulla. Curabitur et vestibulum velit, et pellentesque lacus. Suspendisse sodales tellus at lorem interdum finibus. Mauris venenatis lorem vitae efficitur auctor. Maecenas ultricies, ipsum at iaculis tristique, erat leo porta est, a ullamcorper massa tortor vel odio. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Cras eu libero nibh. Duis dignissim cursus nisl, vitae sagittis ligula sodales a. Mauris semper mi et eleifend pulvinar.

      Ut pharetra lacus magna, ac feugiat metus eleifend ac. Duis congue risus quis lobortis tincidunt. Vivamus accumsan enim eu ornare eleifend. Etiam dignissim, mi nec cursus pellentesque, erat ipsum tristique velit, vitae luctus augue lacus ullamcorper dui. Quisque eleifend dui ut nulla mollis pellentesque. Donec eros risus, fermentum vel arcu eu, posuere mollis felis. Donec mauris augue, convallis in bibendum sed, cursus sit amet mauris. Duis sit amet molestie velit. Curabitur nulla purus, aliquet a fermentum non, tincidunt eu dui. Sed vulputate, orci vitae vulputate cursus, dui lacus imperdiet justo, id eleifend sem odio nec tortor. Maecenas accumsan tempor orci, venenatis cursus enim accumsan sit amet. Donec dignissim rutrum quam, at blandit leo porta vel. Donec eu rhoncus ligula, vitae viverra urna. Nullam tempus leo eget volutpat sodales. Ut dictum, diam vel sagittis convallis, mi nulla vulputate ligula, sit amet interdum nibh magna a tortor.

      Ut ornare pharetra arcu, ac dictum est maximus vel. Vivamus tortor mauris, mollis eget ex non, auctor consequat tortor. Nullam eu neque facilisis, venenatis velit ut, commodo libero. Etiam blandit diam id metus consequat tristique. Etiam elementum felis orci, sit amet vulputate nisi tincidunt in. Praesent scelerisque aliquet felis nec mattis. Nam ipsum mauris, scelerisque accumsan mauris id, fringilla rhoncus diam. Nulla hendrerit enim ac tincidunt vestibulum. Duis quis pulvinar libero. In luctus eros eu massa efficitur facilisis. Sed mi libero, sodales at suscipit eu, congue sit amet risus. Nunc mauris turpis, mollis vitae tincidunt sed, aliquam id metus. Sed viverra ut sapien id fringilla. Praesent id nisi non eros pellentesque lacinia et non tortor. Mauris a tempus sapien.

      Aenean lobortis sem et massa scelerisque ultrices. Fusce et augue hendrerit, luctus mi in, varius nulla. Nullam consectetur vestibulum magna vel malesuada. Nullam ultricies massa at magna laoreet, consectetur bibendum lectus tristique. Curabitur nec ullamcorper odio, vitae cursus urna. Vivamus tristique nibh nunc, vel dignissim mi molestie in. Donec volutpat tortor leo, vitae elementum turpis placerat vel. Aenean non sodales arcu, non egestas quam. Vestibulum porttitor nibh in quam malesuada sodales. Praesent ullamcorper in massa quis accumsan. Nunc mattis tincidunt viverra.
    </Box>
  );
};

export default Home;
